config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'home/bio', to: 'home#bio'
  # get 'cars/new', to: 'cars#new'
  get 'cars/all', to: 'cars#all'
  get '/signup', to: 'users#new'
  resources :cars
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
   validates :plate_number, presence:true, length: { minimum: 4, maximum: 8 }
   validates :time_in, presence:true
   validates :time_out, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cars
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: {case_sensitivity: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitivity: false}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
        flash[:danger] = 'You gotta login brah'
        redirect_to login_path
      end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @car = Car.new
  end
  def create
  @car = Car.new(car_params)
  @car.user = current_user
  if @car.save
    flash[:notice] = "New Car Parked"
    redirect_to car_path(@car)
  else
    render 'new'
  end
end

def show
  @car = Car.find(params[:id])
end

def index
  @car = Car
end

def edit
  @car = Car.find(params[:id])
end

def update
  @car = Car.find(params[:id])
  @car = Car.update(car_params)
  flash[:notice] = 'nice'
  redirect_to car_path(@car)
end

def destroy
  @car = Car.find(params[:id])
  @car.destroy
  flash[:notice] = 'cool'
  redirect_to cars_path
end


private
  def car_params
    params.require(:car).permit(:plate_number, :time_in, :time_out, :color, :brand)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    # debugger
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = "tanga amputa"

      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New User"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def index
    @user = User
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user = User.update(user_params)
    flash[:notice] = 'nice'
    redirect_to users_path(@user)
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'cool'
    redirect_to users_path
  end
  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for @car do |s| %>
  <p>
    <%= s.label :plate_number %>
    <%= s.text_field :plate_number %>
  </p>
  <p>
    <%= s.label :time_in %>
    <%= s.datetime_field :time_in %>
  </p>
  <p>
    <%= s.label :time_out %>
    <%= s.datetime_field :time_out %>
  </p>
  <p>
    <%= s.label :color %>
    <%= s.select :color, ['White', 'Black', 'Silver', 'Red', 'Blue', 'Yellow'] %>
  </p>
  <p>
    <%= s.label :brand %>
    <%= s.select :brand, ['Honda', 'Toyota', 'Ford', 'BMW', 'Mercedes', 'Ferrari', 'Hyundai', 'Porsche'] %>
  </p>
  <p>
      <%= s.submit %>
<% end %>

app/views/cars/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= render "form" %>
  </body>
</html>

app/views/cars/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1 id='title'>Cars</h1>
    <div id='center'><div id="subhead">
      <% if @car.count < 1 %>
      <h1 id="subhead">No cars parked.</h1>
      <% end %>
      <% @car.find_each do |car| %>
      <p>
        Plate Number: <%= car.plate_number %>
      </p>
      <p>
        ID: <%= car.id %>
      </p>
      <p>
        Time In: <%= car.time_in %>
      </p>
      <p>
        Time Out: <%= car.time_out %>
      </p>
      <p>
        Color: <%= car.color %>
      </p>
      <p>
        Brand: <%= car.brand %>
      </p>
      <p>
        Created At: <%= car.created_at %>
      </p>
      <p>
        Updated At: <%= car.updated_at %>
      </p>
      <%=
        link_to 'EDIT', edit_car_path(car)
      %>
      <%=
       link_to 'DELETE', car_path(car), method: :delete, data: {confirm: "u sure?"}
     %>
    </br>
      <% end %>
    </div></div>
    <div id='center'>
      <%=
        link_to 'Back', new_car_path, id: 'link'
      %>

      </div>
        </div>    </div>
  </body>
</html>

app/views/cars/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>



    <h1 id="title">Add a Car</h1>


    <div id='center'><div id="content">
      <%= render "form" %>
  </div></div>

  <div id="center"><div id="content">
    <% if @car.errors.any? %>
  <h2>Errors:</h2>
  <ul>
    <% @car.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </ul>
  <% end %>
  </div></div>
  <div id='showall'><div id="center"><div id="subhead">
    <span>
    <%= link_to 'Show All Cars', cars_path, id: 'link'%>
  </span>
  </div>
  <div></br>
  <%=
    link_to 'Back', home_bio_path, id: 'link'
  %>
</div>
  </div>

  </div>
  </body>
</html>

app/views/cars/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1 id='title'>Car Parked!</h1>
    <div id='center'><div id="subhead">
<style="font-color:white">
<p>
  Plate Number: <%= @car.plate_number %>
</p>
<p>
  Time In: <%= @car.time_in %>
</p>
<p>
  Time Out: <%= @car.time_out %>
</p>
<p>
  Color: <%= @car.color %>
</p>
<p>
  Brand: <%= @car.brand %>
</p>
<p>
  Owner: <%= @car.user.username %>
</p>
<!-- <p>
  Created At: <%= @car.created_at %>
</p> -->
<p>
  Created At: <%= time_ago_in_words(@car.created_at) %> ago
  </p>
<p>
  Updated At: <%= @car.updated_at %>
</p>
</style>
<div id='link'>
<%=
  link_to 'Back', new_car_path, id: 'link'
%></div>
    </div>    </div>
  </body>
</html>

app/views/home/bio.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id="center">
<h1 id='title'>About Me</h1>
<h1 id='subhead'>Paolo Sanchez</h1>
<img id='dp' src="https://scontent.fmnl4-6.fna.fbcdn.net/v/t31.0-8/21246295_1997304056953942_4081317352325295172_o.jpg?_nc_cat=106&oh=20b5af8cbecab4f28e447792a5fb6c07&oe=5C58FB9A">
<h1 id='content'>I am Paolo Sanchez, a 3 BS MIS student studying under the best MIS 21 prof named Jacob Chua. I am 20 years young and I love Apple. I like Nancy and Yeonwoo from Momoland. I went to Hong Kong Baptist University for STA. We had a GUI for git commands so we never memorized how to git güd. My favorite git is the gitara. My favorite song is The Middle by Zedd ft. some other girl. This song is my favorite git because in Filipino it's translated to Sa Gitna.</h1>
</div>
<div id="center">
  <%=
    link_to 'Parking Lot', new_car_path, id: 'link'
  %>
  </br>
  <%=
    link_to 'Users', users_path, id: 'link'
  %></div>
  </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
<div id="center"><h1 id="title">Welcome to The Parking Lot</h1>

<%=
  link_to 'Bio', home_bio_path, id: 'link'
%>
</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
  <ul>
    <li>
    <%= msg %>
    </li>
  </ul>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |s| %>
  <p>
    <%= s.label :username %>
    <%= s.text_field :username %>
  </p>
  <p>
    <%= s.label :email %>
    <%= s.text_field :email %>
  </p>
  <p>
    <%= s.label :password %>
    <%= s.password_field :password %>
  </p>
  <p>
      <%= s.submit %>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= render "form" %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1 id='title'>Users</h1>
    <div id='center'><div id="subhead">
      <% if logged_in? %>
      <%= link_to 'logout', logout_path, method: :delete %>
      <% else %>
      <%= link_to 'login', login_path %>
      <% end %>
      <% if @user.count < 1 %>
      <h1 id="subhead">No users registered.</h1>
      <% end %>
      <div id='center'><div id="subhead">
      <% @user.find_each do |user| %>
  <p>
    Username: <%= link_to user.username, user_path(user) %>
  </p>
  <p>
    Email: <%= user.email %>
  </p>
  <p>
    Password: <%= user.password %>
  </p>
  <p>
    Cars logged: <%= user.cars.count %>
  </p>

    <%=
      link_to 'EDIT', edit_user_path(user)
    %>
    <%=
     link_to 'DELETE', user_path(user), method: :delete, data: {confirm: "u sure?"}
   %>
   </br>
          <% end %>
          </br></br></br>
            <div id='link'>
              <%=
                link_to 'Create New User', signup_path, id: 'link'
              %></br>
              <%=
                link_to 'Back', home_bio_path, id: 'link'
              %></div>

      </div>    </div>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>



    <h1 id="title">Add a User</h1>


    <div id='center'><div id="content">
      <%= render "form" %>
  </div></div>

  <div id="center"><div id="content">
    <% if @user.errors.any? %>
  <h2>Errors:</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </ul>
  <% end %>
  </div></div>
  <div id='showall'><div id="center"><div id="subhead">
    <span>
     <!-- rails link_to 'Show Users Cars', users_path, id: 'link'%> -->
     <%=
       link_to 'Back', users_path, id: 'link'
     %>
  </span>
  </div>
  </div>

  </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <% if logged_in? %>
    <h1>logged in nigga!</h1>
    <% else %>
    <h1 id='title'>User Created!</h1>
    <% end %>
    <div id='center'><div id="subhead">

<p>
  Username: <%= @user.username %>
</p>
<p>
  Email: <%= @user.email %>
</p>
<p>
  Password: <%= @user.password %>
</p>
<p>
  Cars logged: <%= @user.cars.count %>
</p>

<% @user.cars.find_each do |car| %>
<p>
  Plate Number: <%= car.plate_number %>
</p>
<p>
  Time In: <%= car.time_in %>
</p>
<p>
  Time Out: <%= car.time_out %>
</p>
<p>
  Color: <%= car.color %>
</p>
<p>
  Brand: <%= car.brand %>
</p>
<p>
  Owner: <%= car.user.username %>
</p>
<!-- <p>
  Created At: <%= car.created_at %>
</p> -->
<p>
  Created At: <%= time_ago_in_words(car.created_at) %> ago
  </p>
<p>
  Updated At: <%= car.updated_at %>
</p>
          <% end %>
<div id='link'>
  <%=
    link_to 'Create New User', signup_path, id: 'link'
  %>

</br>
  <%=
    link_to 'Back', home_bio_path, id: 'link'
  %></div>
    </div>    </div>
  </body>
</html>